# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name CLap
#' @title Laplace sample by Rcpp
#' @description Generate the Laplace sample by Rcpp,using the normal distribution
#' @param sigma the SD of Normal distribution
#' @param x0 the first data
#' @param N the sample size
#' @return a list,x stands for random sample of Laplace sample,k is the acceptance number
#' @examples
#' \dontrun{
#' res <- CLap(sigma,x0,N)
#' }
#' @export
CLap <- function(sigma, x0, N) {
    .Call(`_StatComp20077_CLap`, sigma, x0, N)
}

rcpp_hello <- function() {
    .Call(`_StatComp20077_rcpp_hello`)
}

